### ISSUE TITLE
Infos throw error because of 'unset'

### ISSUE THREAD

**Issue by kensain** [Axlefublr/lib-v2#1]
When script is started, there is an initial error for all 3 `unset` parameters. The script works fine if the errors are ignored. When restarted - happens again:
![image](https://user-images.githubusercontent.com/69140574/208682510-7e25a9e5-cae4-4636-b86c-fcbbb9b34a17.png)

**Comment by Axlefublr** [comment]
Your v2 version is old: after I think beta 15, you now can explicitly set `unset` to variables, so update to remove this issue
